/**
 * Some test comment
 */
// Other comment
module Example {
    // Basic types example
    typedef long MyLong;
//    typedef string MyString; //parser can't yet handle strings here

    // Enum example
    enum Status {
        ACTIVE,
        INACTIVE,
        PENDING
    };

    // Second enum example
    enum HwType : uint16 {
        // This is the default value
        UNDEFINED   = 0xffff,
        // This is a StarFishDaq
        SFDQ        = 0x0000,
        BLUE_SERVO  = 0x0001,
        LUMEN       = 0x0002,
        // The ST family of development PCBs
        NUCLEO      = 0x0003,
        BLUE_ESC    = 0x0004,
        GIGABOARD   = 0x0005,
        BLUE_BRIDGE	= 0x0006
    };

    // Struct example
    struct Person {
        string name;
        long age;
        boolean isActive;
    };

    // Sequence example
    typedef sequence<long> LongList;
 //   typedef sequence<string, 100> BoundedStringList;//parser can't handle sequences of strings yet
    typedef sequence<Person> PersonList;

    // Nested sequences
//    typedef sequence<sequence<long>> Matrix;//not sure this is legal. Either way, parser can't handle it yet. Work around is to define a sequence type and then another
};
