/*
Copyright (c) 2025  Blue Robotics North Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

/*
 *The purpose of this module is to test module functionality
 */
module ThisIsATestModule::AndAnother {
	//this defines the numerical namespace that official blueberry messages will live within


	typedef uint16 BlahType[10];
	typedef float Matrix3x3[3][3];
	typedef uint32 AnotherType;
	const uint16 THIS_IS_A_CONSTANT = 0x42;
	const string THIS_IS_A_STRING_CONSTANT = "blahblahblah";


	enum TestEnum {
		UNDEFINED = 65536,
		FIRST_VALUE,
		SECOND_VALUE = 12,
		THIRD_VALUE,
		FOURTH_VALUE = 33,
		FIFTH_VALUE,
		SIXTH_VALUE = 34
	};



	/*
	 A message to convey hardware and firmware versions in addition to hardware type
	 */
	@topic("blueberry/devices/{device_type}/{nid}/test")
	@revision(1)
	message TestMessage {
		string <20> filename;


	};

};

import ThisIsATestModule;
//A demo struct to debug stuff
struct TestStruct {
	ThisIsATestModule::AndAnother::BlahType test4; //a nested defined type
	AndAnother::Matrix3x3 test9;
	uint8 test5;
	boolean test10;
	string <20> test12;
};

typedef sequence <TestStruct> TestSequence;
typedef TestStruct TestStructArray[2];
typedef TestSequence TestSequenceArray[3];
module ThisIsATestModule {
	module AndAnother	{
		/*
		 A message to convey hardware and firmware versions in addition to hardware type
		 */
		@topic("blueberry/devices/{device_type}/{nid}/test2")
		@revision(0)
		message Test2Message {
			::ThisIsATestModule::AndAnother::BlahType test6;
			BlahType test14;//a test field
			TestStruct test7; //for testing.
			boolean test8;
			TestSequence test11;
			TestStructArray test44;
			TestSequenceArray test55;
		};
	};
};
